kind: Template
apiVersion: v1
objects:

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      selector:
        app: ocp101-demo
        deploymentconfig: ocp101-demo
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: ocp101-demo
            deploymentconfig: ocp101-demo
        spec:
          containers:
            - image: >-
                docker-registry.default.svc:5000/ocp101a-tools/ocp101-demo:${CHANGE_ID}
              name: ocp101-demo
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ocp101-demo
            from:
              kind: ImageStreamTag
              name: 'ocp101-demo:${CHANGE_ID}'
              namespace: ocp101a-tools
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ocp101-demo
      name: ocp101-demo-${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      host: ''
      port:
        targetPort: 8080-tcp
      to:
        kind: ''
        name: ocp101-demo-${SUFFIX}
        weight: null
    metadata:
      labels:
        app: ocp101-demo
      name: ocp101-demo-${SUFFIX}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 3000
          protocol: TCP
          targetPort: 8080
      selector:
        app: ocp101-demo
        deploymentconfig: ocp101-demo
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: >
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"ocp101-demo"},"name":"ocp101-demo","namespace":"ocp101a-dev"},"spec":{"ports":[{"name":"8080-tcp","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"ocp101-demo","deploymentconfig":"ocp101-demo"}},"status":{"loadBalancer":{}}}
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ocp101-demo
      name: ocp101-demo-${SUFFIX}
parameters:
- name: SUFFIX
  description: identifies each deployment
  value: 'foo'
- name: CHANGE_ID
  description: the pr number
  value: '0'
